version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - GOOGLE_CLOUD_LOCATION=${GOOGLE_CLOUD_LOCATION}
      - MAS_AGENT_ID=${MAS_AGENT_ID}
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/app/credentials.json
    env_file:
      - ./backend/.env
    networks:
      - mas-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8000
      - REACT_APP_WS_URL=ws://backend:8000
    networks:
      - mas-network

networks:
  mas-network:
    driver: bridge